timeout: 5
default_entry=0
graphics=yes
resolution=auto
ui_branding="LavaOS"
ui_branding_foreground_colour=0xC0C0C0C0
ui_branding_background_colour=0x00000000

ui_menu_foreground_colour=0xC0C0C0C0
ui_menu_background_colour=0x00000000
ui_menu_selection_foreground_colour=0x00000000
ui_menu_selection_background_colour=0xC0C0C0C0

ui_hint_foreground_colour=0xFFC0C0C0
ui_hint_background_colour=0x00000000

/LavaOS
    comment="Boot the LavaOS operating system"
    protocol: limine
    kernel_path: boot():/kernel
    module_path: boot():/initrd
    cmdline:
/Reboot
    comment="Reboot"
    protocol=reboot
/Poweroff
    comment="Poweroff"
    protocol=poweroff
